// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEB0ZefYP7Ff4lr68SfB21qO1EKGsEvLE',
    appId: '1:691123653494:web:80bafdd296cb133a608857',
    messagingSenderId: '691123653494',
    projectId: 'projet-flutter-403f0',
    authDomain: 'projet-flutter-403f0.firebaseapp.com',
    storageBucket: 'projet-flutter-403f0.firebasestorage.app',
    measurementId: 'G-CZEDRY6ZY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwH6BFCzqCsaiuIfQjV5d0IfIswVCREmM',
    appId: '1:691123653494:android:ac62763dff9606a7608857',
    messagingSenderId: '691123653494',
    projectId: 'projet-flutter-403f0',
    storageBucket: 'projet-flutter-403f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5SeZEq3r92t-crYDRUSyREtujRDhv5GQ',
    appId: '1:691123653494:ios:1864271ff48227dc608857',
    messagingSenderId: '691123653494',
    projectId: 'projet-flutter-403f0',
    storageBucket: 'projet-flutter-403f0.firebasestorage.app',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5SeZEq3r92t-crYDRUSyREtujRDhv5GQ',
    appId: '1:691123653494:ios:1864271ff48227dc608857',
    messagingSenderId: '691123653494',
    projectId: 'projet-flutter-403f0',
    storageBucket: 'projet-flutter-403f0.firebasestorage.app',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEB0ZefYP7Ff4lr68SfB21qO1EKGsEvLE',
    appId: '1:691123653494:web:e50d4c8652ec92e3608857',
    messagingSenderId: '691123653494',
    projectId: 'projet-flutter-403f0',
    authDomain: 'projet-flutter-403f0.firebaseapp.com',
    storageBucket: 'projet-flutter-403f0.firebasestorage.app',
    measurementId: 'G-24SCT4HSQB',
  );

}